DVD-Samling/Areas/Admin/Controllers/GenreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DVD_Samling.Data;
using DVD_Samling.Models;
using DVD_Samling.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DVD_Samling.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class GenreController : Controller
    {
        private readonly ApplicationDbContext _db;
        public GenreController(ApplicationDbContext db)
        {
            _db = db;
        }

        //Get all Genre
        public async Task<IActionResult> Index()
        {

            return View(await _db.Genre.ToListAsync());
        }

        //Get - Create
        public IActionResult Create()
        {
            return View();
        }

        //POST -CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _db.Add(genre);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }


        //EDIT - GET
        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var genre = await _db.Genre.FindAsync(id);
            if(genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        //EDIT - POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _db.Update(genre);
                await _db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(genre);
        }

        //DELETE - GET
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var genre = await _db.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }

        //DELETE - POST
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            var genre = await _db.Genre.FindAsync(id);

            if(genre == null)
            {
                return View();
            }
            _db.Genre.Remove(genre);
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var genre = await _db.Genre.FindAsync(id);
            if (genre == null)
            {
                return NotFound();
            }
            return View(genre);
        }
    }
}

DVD-Samling/Areas/Admin/Controllers/MovieItemController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DVD_Samling.Data;
using DVD_Samling.Models;
using DVD_Samling.Models.ViewModels;
using DVD_Samling.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DVD_Samling.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class MovieItemController : Controller
    {
        private readonly ApplicationDbContext _db;
        //Dette er til upload af billeder
        private readonly IWebHostEnvironment _webHostEnviroment;

        [BindProperty]
        public MovieItemViewModel MovieItemVM { get; set; }

        public MovieItemController(ApplicationDbContext db, IWebHostEnvironment webHostEnviroment)
        {
            _db = db;
            _webHostEnviroment = webHostEnviroment;
            MovieItemVM = new MovieItemViewModel()
            {
                genre = _db.Genre,
                MovieItem = new Models.MovieItem()
            };
        }
        public async Task<IActionResult> Index()
        {

            var movieItem = await _db.movieItems.Include(m => m.Genre).ToListAsync();
            return View(movieItem);
        }


        public IActionResult Create()
        {
            return View(MovieItemVM);
        }

        [HttpPost, ActionName("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePOST()
        {
            if (!ModelState.IsValid)
            {
                return View(MovieItemVM);
            }

            _db.movieItems.Add(MovieItemVM.MovieItem);
            await _db.SaveChangesAsync();

            //Saveing image

            string webRootPath = _webHostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var MovieItemFromDb = await _db.movieItems.FindAsync(MovieItemVM.MovieItem.Id);

            if(files.Count > 0)
            {
                //If image was uploaded 
                var uploads = Path.Combine(webRootPath, "images");
                var extension = Path.GetExtension(files[0].FileName);

                using (var filesStream = new FileStream(Path.Combine(uploads, MovieItemVM.MovieItem.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);
                }
                MovieItemFromDb.Image = @"\images\" + MovieItemVM.MovieItem.Id + extension;

            }
            else
            {
                //If no image was uploaded, so use default image
                var uploads = Path.Combine(webRootPath, @"images\" + SD.DefaultMovieImage);
                System.IO.File.Copy(uploads, webRootPath + @"\images\" + MovieItemVM.MovieItem.Id + ".png");
                MovieItemFromDb.Image = @"\images\" + MovieItemVM.MovieItem.Id + ".png";
            }

            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            MovieItemVM.MovieItem = await _db.movieItems.Include(m => m.Genre).SingleOrDefaultAsync(m => m.Id == id);

            if(MovieItemVM.MovieItem == null)
            {
                return NotFound();
            }
            return View(MovieItemVM);
        }

        [HttpPost, ActionName("edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPOST(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                return View(MovieItemVM);
            }



            //Saveing image

            string webRootPath = _webHostEnviroment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var MovieItemFromDb = await _db.movieItems.FindAsync(MovieItemVM.MovieItem.Id);

            if (files.Count > 0)
            {
                //New image has been uploaded 
                var uploads = Path.Combine(webRootPath, "images");
                var extension_new = Path.GetExtension(files[0].FileName);

                //Delete the original image
                var imagePath = Path.Combine(webRootPath, MovieItemFromDb.Image.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }


                //upload new image
                using (var filesStream = new FileStream(Path.Combine(uploads, MovieItemVM.MovieItem.Id + extension_new), FileMode.Create))
                {
                    files[0].CopyTo(filesStream);
                }
                MovieItemFromDb.Image = @"\images\" + MovieItemVM.MovieItem.Id + extension_new;

            }

            MovieItemFromDb.Name = MovieItemVM.MovieItem.Name;
            MovieItemFromDb.Description = MovieItemVM.MovieItem.Description;
            MovieItemFromDb.Subtitels = MovieItemVM.MovieItem.Subtitels;
            MovieItemFromDb.GenreId = MovieItemVM.MovieItem.GenreId;
            MovieItemFromDb.Agelimit = MovieItemVM.MovieItem.Agelimit;
            await _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        //Get all details on film
        public async Task<IActionResult> Details(int? id)
        {
            if(id == null)
            {
                NotFound();
            }

            MovieItemVM.MovieItem = await _db.movieItems.Include(g => g.Genre).SingleOrDefaultAsync(m => m.Id == id);

            if(MovieItemVM.MovieItem == null)
            {
                NotFound();
            }

            return View(MovieItemVM);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                NotFound();
            }

            MovieItemVM.MovieItem = await _db.movieItems.Include(g => g.Genre).SingleOrDefaultAsync(m => m.Id == id);

            if(MovieItemVM.MovieItem == null)
            {
                NotFound();
            }

            return View(MovieItemVM);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            string webRootPath = _webHostEnviroment.WebRootPath;

            MovieItem movieItem = await _db.movieItems.FindAsync(id);

            if( movieItem != null)
            {
                var imagePath = Path.Combine(webRootPath, movieItem.Image.TrimStart('\\'));

                if (System.IO.File.Exists(imagePath))
                {
                    System.IO.File.Delete(imagePath);
                }

                _db.movieItems.Remove(movieItem);
                await _db.SaveChangesAsync();

            }

            return RedirectToAction(nameof(Index));
        }
    }
}

DVD-Samling/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using DVD_Samling.Data;
using DVD_Samling.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DVD_Samling.Areas.Admin.Controllers
{
    [Authorize(Roles = SD.ManagerUser)]
    [Area("Admin")]
    public class UserController : Controller
    {
        private readonly ApplicationDbContext _db;

        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            return View(await _db.ApplicationUsers.Where(u => u.Id != claim.Value).ToListAsync());
        }

        public async Task<IActionResult> Lock(string id)
        {
            if(id == null)
            {
                NotFound();
            }

            var applicationUser = await _db.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == id);

            if(applicationUser == null)
            {
                NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now.AddYears(100);

            _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                NotFound();
            }

            var applicationUser = await _db.ApplicationUsers.FirstOrDefaultAsync(u => u.Id == id);

            if (applicationUser == null)
            {
                NotFound();
            }

            applicationUser.LockoutEnd = DateTime.Now;

            _db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

DVD-Samling/Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="Opret" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Tilbage til listen</a>
    </div>
</div>

DVD-Samling/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; Opret</a>
</p>

DVD-Samling/Views/Shared/_DeleteAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-id="@Model" value="Slet" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Tilbage til listen</a>
    </div>
</div>

DVD-Samling/Views/Shared/_DetailsAndBackToListButton.cshtml
@model int


<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-id="@Model" class="btn btn-info form-control">Redigere</a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Tilbage til listen</a>
    </div>
</div>

DVD-Samling/Views/Shared/_EditAndBackToListButton.cshtml
@model int

<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-id="@Model" value="Opdater" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">Tilbage til listen</a>
    </div>
</div>

DVD-Samling/Views/Shared/_GenreTableButton.cshtml
@model int


<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" style="margin-right:40px" asp-action="Edit" asp-route-Id="@Model"><i class="fas fa-edit"></i></a>

       

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model"><i class="fas fa-trash-alt"></i></i></a>
    </div>
</td>

DVD-Samling/Views/Shared/_Layout.cshtml
@using DVD_Samling.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DVD_Samling</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/23be5db119.js" crossorigin="anonymous"></script>
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <label class="text-info" style="cursor:pointer">DVD_Samling</label>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Genre" asp-area="Admin">Genre</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MovieItem" asp-area="Admin">Film</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">Bruger</a>
                                    <a class="dropdown-item">Udlånt</a>
                                </div>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssRentalCartCount) != null)
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32(@SD.ssRentalCartCount);
                                    }
                                    <i class="fas fa-compact-disc"></i> &nbsp; (@count)
                                </a>
                            </li>
                        }
                        else
                        {
                            <li style="color:white">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-compact-disc"></i> &nbsp; (0)
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top pl-3 footer text-white-50" style="background-color: #343a40">
        <div class="container">
            &copy; 2020 - DVD_Samling - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

DVD-Samling/Views/Shared/_TableButtonPartial.cshtml
@model int


<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white" asp-action="Edit" asp-route-Id="@Model"><i class="fas fa-edit"></i></a>

        <a class="btn btn-success text-white" asp-action="Details" asp-route-Id="@Model"><i class="fas fa-list-alt"></i></i></a>

        <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@Model"><i class="fas fa-trash-alt"></i></i></a>
    </div>
</td>

DVD-Samling/Views/Shared/_ThumbnailAreaPartial.cshtml
@model IEnumerable<MovieItem>


@if(Model.Count() > 0)
{
    <div class="col-12 post @Model.FirstOrDefault().Genre.Name.Replace(" ",string.Empty) movie-shop">
        <div class="row">
            <h3 class="text-success">@Model.FirstOrDefault().Genre.Name</h3>
        </div>

        @foreach(var item in Model)
        {
            <div class="border border-info rounded col-12" style="margin-bottom:10px; margin-top:10px; padding:10px;">
                <div class="row">
                    <div class="col-md-3 col-sm-12">
                        <img src="@item.Image" width="99%" style="border-radius:5px; border:1px solid #bbb9b9" />
                    </div>
                    <div class="col-md-9 col-sm-12">
                        <div class="row pr-3">
                            <div class="col-8">
                                <label class="text-primary" style="font-size:24px; color:mediumblue">@item.Name</label>
                                @if (item.Agelimit == "0")
                                {
                                    <img srcset="/images/Tilladt_for_all.png" title="All" />
                                }
                                @if (item.Agelimit == "1")
                                {
                                    <img srcset="/images/Frarådes_for_børnunder_7.png" title="Age7" />
                                }
                                @if (item.Agelimit == "2")
                                {
                                    <img srcset="/images/Tilladt_fra_11_år.png" title="Age11" />
                                }
                                @if (item.Agelimit == "3")
                                {
                                    <img srcset="/images/Tilladt_fra_15_år.png" title="Age15" />
                                }
                            </div>

                        </div>

                        <div class="row col-12 text-justify d-none d-md-block">
                            <p>@Html.Raw(item.Description)</p>
                        </div>
                        <div class="col-12 align-bottom text-left" style="color:mediumblue">
                            <p>Undertexter: @item.Subtitels</p>
                        </div>
                        <div class="col-md-3 col-sm-12 offset-md-9 text-center">
                            <a asp-action="Details" class="btn btn-success form-control" asp-route-id="@item.Id">Detajler</a>
                        </div>
                    </div>
                    </div>
                </div>
        }
        <div class="p-4"></div>
    </div>
}